#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "qrcodegen.h"

// Function to print QR code to console as ASCII art
void printQR(const uint8_t qrcode[]) {
    int size = qrcodegen_getSize(qrcode);
    int border = 4;
    
    printf("\nQR Code (Version: %d, Size: %dx%d):\n", 
           ((size - 17) / 4), size, size);
    
    // Print top border
    for (int i = 0; i < size + border * 2; i++) {
        printf("██");
    }
    printf("\n");
    
    // Print QR code with borders
    for (int y = -border; y < size + border; y++) {
        // Left border
        for (int i = 0; i < border; i++) {
            printf("██");
        }
        
        // QR code content
        for (int x = 0; x < size; x++) {
            if (y < 0 || y >= size) {
                printf("██");  // Top/bottom border
            } else {
                printf(qrcodegen_getModule(qrcode, x, y) ? "  " : "██");
            }
        }
        
        // Right border
        for (int i = 0; i < border; i++) {
            printf("██");
        }
        printf("\n");
    }
    
    // Print bottom border
    for (int i = 0; i < size + border * 2; i++) {
        printf("██");
    }
    printf("\n");
}

// Function to save QR code as PBM (Portable Bitmap) image
int saveQRAsPBM(const uint8_t qrcode[], const char* filename) {
    int size = qrcodegen_getSize(qrcode);
    int border = 4;
    int imageSize = size + 2 * border;
    
    FILE* file = fopen(filename, "w");
    if (file == NULL) {
        printf("Error: Could not create file %s\n", filename);
        return 0;
    }
    
    // Write PBM header
    fprintf(file, "P1\n");
    fprintf(file, "# QR Code generated by qrcodegen library\n");
    fprintf(file, "%d %d\n", imageSize, imageSize);
    
    // Write image data
    for (int y = -border; y < size + border; y++) {
        for (int x = -border; x < size + border; x++) {
            if (y < 0 || y >= size || x < 0 || x >= size) {
                fprintf(file, "0 ");  // White border
            } else {
                fprintf(file, "%d ", qrcodegen_getModule(qrcode, x, y) ? 1 : 0);
            }
        }
        fprintf(file, "\n");
    }
    
    fclose(file);
    return 1;
}

// Function to generate QR code with specific version
int generateQRCode(const char* text, int version, enum qrcodegen_Ecc ecl) {
    // Calculate buffer size for the specified version
    size_t bufferSize = qrcodegen_BUFFER_LEN_FOR_VERSION(version);
    
    // Allocate buffers
    uint8_t* qrcode = malloc(bufferSize);
    uint8_t* tempBuffer = malloc(bufferSize);
    
    if (qrcode == NULL || tempBuffer == NULL) {
        printf("Error: Memory allocation failed\n");
        free(qrcode);
        free(tempBuffer);
        return 0;
    }
    
    // Generate QR code
    bool ok = qrcodegen_encodeText(text, tempBuffer, qrcode, ecl, 
                                   version, version, qrcodegen_Mask_AUTO, true);
    
    if (!ok) {
        printf("Error: Failed to generate QR code\n");
        free(qrcode);
        free(tempBuffer);
        return 0;
    }
    
    int actualVersion = (qrcodegen_getSize(qrcode) - 17) / 4;
    printf("Generated QR Code - Requested Version: %d, Actual Version: %d\n", 
           version, actualVersion);
    
    // Print QR code to console
    printQR(qrcode);
    
    // Save as PBM image
    char filename[256];
    snprintf(filename, sizeof(filename), "qrcode_v%d.pbm", actualVersion);
    
    if (saveQRAsPBM(qrcode, filename)) {
        printf("\nQR Code saved as: %s\n", filename);
        printf("You can view this PBM file with image viewers or convert it to other formats.\n");
    }
    
    // Save as text representation
    snprintf(filename, sizeof(filename), "qrcode_v%d.txt", actualVersion);
    FILE* txtFile = fopen(filename, "w");
    if (txtFile != NULL) {
        int size = qrcodegen_getSize(qrcode);
        fprintf(txtFile, "QR Code (Version %d, Size: %dx%d)\n", actualVersion, size, size);
        fprintf(txtFile, "Text: %s\n\n", text);
        
        for (int y = 0; y < size; y++) {
            for (int x = 0; x < size; x++) {
                fprintf(txtFile, qrcodegen_getModule(qrcode, x, y) ? "██" : "  ");
            }
            fprintf(txtFile, "\n");
        }
        fclose(txtFile);
        printf("Text representation saved as: %s\n", filename);
    }
    
    free(qrcode);
    free(tempBuffer);
    return 1;
}

int main() {
    printf("=== QR Code Generator ===\n");
    printf("Using Nayuki's QR-Code-generator library\n\n");
    
    // Test data for different scenarios
    const char* testTexts[] = {
        "Hello QR!",                    // Short text for version 1-2
        "https://github.com",           // URL for version 2-3
        "QR Code Version 3 Test Data",  // Medium text for version 3
        "This is a longer text message that should require version 3 or higher for QR code generation testing purposes." // Long text
    };
    
    const char* descriptions[] = {
        "Short message",
        "GitHub URL",
        "Version 3 test text",
        "Long message"
    };
    
    int numTests = sizeof(testTexts) / sizeof(testTexts[0]);
    
    // Generate QR codes with different error correction levels
    enum qrcodegen_Ecc eccLevels[] = {
        qrcodegen_Ecc_LOW,
        qrcodegen_Ecc_MEDIUM,
        qrcodegen_Ecc_QUARTILE,
        qrcodegen_Ecc_HIGH
    };
    
    const char* eccNames[] = {
        "Low",
        "Medium", 
        "Quartile",
        "High"
    };
    
    // Generate QR codes for version 3 specifically
    printf("Generating QR codes targeting Version 3:\n");
    printf("=========================================\n\n");
    
    for (int i = 0; i < numTests; i++) {
        printf("Test %d: %s\n", i + 1, descriptions[i]);
        printf("Text: \"%s\"\n", testTexts[i]);
        printf("Length: %zu characters\n", strlen(testTexts[i]));
        
        // Try with medium error correction first
        if (!generateQRCode(testTexts[i], 3, qrcodegen_Ecc_MEDIUM)) {
            printf("Failed to generate QR code for test %d\n", i + 1);
        }
        
        printf("\n" "----------------------------------------\n\n");
    }
    
    // Interactive mode
    printf("Interactive Mode:\n");
    printf("================\n");
    printf("Enter text to generate a QR code (or 'quit' to exit):\n");
    printf("Tips:\n");
    printf("  - Use \\n for newlines (e.g., \"Line 1\\nLine 2\")\n");
    printf("  - Use \\t for tabs\n");
    printf("  - Type 'quit' or 'exit' to exit\n");
    printf("  - Press Enter twice to finish multi-line input\n\n");
    
    char input[1000];
    while (1) {
        printf("> ");
        if (fgets(input, sizeof(input), stdin) == NULL) {
            break;
        }
        
        // Remove newline
        input[strcspn(input, "\n")] = 0;
        
        if (strcmp(input, "quit") == 0 || strcmp(input, "exit") == 0) {
            break;
        }
        
        if (strlen(input) == 0) {
            continue;
        }
        
        // Process escape sequences
        char processed[1000];
        int j = 0;
        for (int i = 0; input[i] != '\0' && j < sizeof(processed) - 1; i++) {
            if (input[i] == '\\' && input[i+1] != '\0') {
                switch (input[i+1]) {
                    case 'n':
                        processed[j++] = '\n';
                        i++; // Skip the next character
                        break;
                    case 't':
                        processed[j++] = '\t';
                        i++; // Skip the next character
                        break;
                    case 'r':
                        processed[j++] = '\r';
                        i++; // Skip the next character
                        break;
                    case '\\':
                        processed[j++] = '\\';
                        i++; // Skip the next character
                        break;
                    default:
                        processed[j++] = input[i];
                        break;
                }
            } else {
                processed[j++] = input[i];
            }
        }
        processed[j] = '\0';
        
        printf("\nGenerating QR code for: \"");
        // Print the text with escape sequences visible
        for (int i = 0; processed[i] != '\0'; i++) {
            if (processed[i] == '\n') {
                printf("\\n");
            } else if (processed[i] == '\t') {
                printf("\\t");
            } else if (processed[i] == '\r') {
                printf("\\r");
            } else {
                printf("%c", processed[i]);
            }
        }
        printf("\"\n");
        generateQRCode(processed, 3, qrcodegen_Ecc_MEDIUM);
        printf("\n");
    }
    
    printf("QR Code generation completed!\n");
    printf("Check the '../output/' directory for generated files.\n");
    return 0;
}
